
name: "4Geeks.com Aquisition"
# You can have as many pipelines as you want
pipelines:
    # Unique name for your pipeline, must match folder name in ./pipelines/<folder_name>
  - slug: "clean_invites"
    # During local development these are CSV files located at te ./sources folder.
    sources:
      # The order is relevant, this sources will be passed as parameters to the run() function in the same order
      - authenticate_userinvite
    # Ignored during local development, its the datasource to wich the pipeline data will be saved to
    destination: cleaned_user_invites
    # Order is relevant, they will execute one on top of the other.
    transformations:
      - build_hello_world